name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  gcc:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:

      - name: checkout project code
        uses: actions/checkout@v2

      - name: CMake Configure
        run: cmake -B build

      - name: CMake build
        run: cmake --build build

      - name: test
        run: ./build/test

  clang:
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - name: checkout project code
        uses: actions/checkout@v2

      - name: CMake Configure
        run: cmake -B build

      - name: CMake build
        run: cmake --build build

      - name: test
        run: ./build/test

  mac:
    runs-on: macos-latest
    env:
      CC: clang
    steps:
      - name: checkout project code
        uses: actions/checkout@v2

      - name: CMake Configure
        run: cmake -B build

      - name: CMake build
        run: cmake --build build

      - name: test
        run: ./build/test

  msvc:
    runs-on: windows-latest
    env:
      CC: msvc
    steps:
      - name: checkout project code
        uses: actions/checkout@v2

      - name: CMake Configure
        run: cmake -B build

      - name: CMake build
        run: cmake --build build

      - name: test
        run: ./build/test
