name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CONFIGURATION: Release

jobs:

  gcc:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:
      - name: checkout project code
        uses: actions/checkout@v2
      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIGURATION }}
      - name: CMake build
        run: cmake --build build
      - name: Test
        run: ./build/test

  gcc-mkl:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:
      - name: checkout project code
        uses: actions/checkout@v2
      - name: set up mkl
        run: |
          sudo apt-get update
          sudo apt-get install -y intel-mkl-full
      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIGURATION }}
      - name: CMake build
        run: cmake --build build
      - name: Test
        run: ./build/test

  gcc-lapack:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:
      - name: checkout project code
        uses: actions/checkout@v2
      - name: set up mkl
        run: |
          sudo apt-get update
          sudo apt-get install -y libblas-dev liblapack-dev
      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIGURATION }}
      - name: CMake build
        run: cmake --build build
      - name: Test
        run: ./build/test

  clang:
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - name: checkout project code
        uses: actions/checkout@v2
      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIGURATION }}
      - name: CMake build
        run: cmake --build build
      - name: Test
        run: ./build/test

  clang-mkl:
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - name: checkout project code
        uses: actions/checkout@v2
      - name: set up mkl
        run: |
          sudo apt-get update
          sudo apt-get install -y intel-mkl-full
      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIGURATION }}
      - name: CMake build
        run: cmake --build build
      - name: Test
        run: ./build/test

  clang-lapack:
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - name: checkout project code
        uses: actions/checkout@v2
      - name: set up mkl
        run: |
          sudo apt-get update
          sudo apt-get install -y libblas-dev liblapack-dev
      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIGURATION }}
      - name: CMake build
        run: cmake --build build
      - name: Test
        run: ./build/test

  mac:
    runs-on: macos-latest
    env:
      CC: clang
    steps:
      - name: checkout project code
        uses: actions/checkout@v2
      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIGURATION }}
      - name: CMake build
        run: cmake --build build
      - name: Test
        run: ./build/test

  msvc:
    runs-on: windows-latest
    env:
      CC: msvc
    steps:
      - name: checkout project code
        uses: actions/checkout@v2
      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIGURATION }}
      - name: CMake build
        run: cmake --build build --config ${{ env.CONFIGURATION }}
      - name: Test
        run: |
          .\build\${{ env.CONFIGURATION }}\test.exe
